phase 15 esemble learning

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    BaggingClassifier,
    AdaBoostClassifier,
    GradientBoostingClassifier,
    VotingClassifier,
    StackingClassifier
)

from sklearn.metrics import accuracy_score

In [5]:


df = pd.read_csv("../data/Global_Cybersecurity_Threats_2015-2024.csv")

In [6]:
df["High_Loss"] = (
    df["Financial Loss (in Million $)"] >
    df["Financial Loss (in Million $)"].median()
).astype(int)

In [8]:
X = df.drop("High_Loss", axis=1)
y = df["High_Loss"]

In [9]:
X = pd.get_dummies(X, drop_first=True)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [11]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(2400, 34)
(600, 34)
(2400,)
(600,)

In [ ]:
#feature 15.1 voting classifier 
from sklearn.ensemble import VotingClassifier

voting_model = VotingClassifier(
    estimators=[
        ("lr", LogisticRegression()),
        ("dt", DecisionTreeClassifier()),
        ("rf", RandomForestClassifier())
    ],
    voting="hard"
)

In [14]:
#feature 15.2 bagging 
from sklearn.ensemble import BaggingClassifier
tree = DecisionTreeClassifier(
    random_state=42
)
bagging_model = BaggingClassifier(
    estimator=tree,
    n_estimators=100,
    random_state=42
)

In [15]:
bagging_model.fit(
    X_train,
    y_train
)

BaggingClassifier(estimator=DecisionTreeClassifier(random_state=42),
                  n_estimators=100, random_state=42)

In [16]:
y_pred = bagging_model.predict(
    X_test
)

In [17]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy :", accuracy)

Accuracy : 1.0

In [19]:
#15.3 boosting 
from sklearn.ensemble import AdaBoostClassifier
adaboost_model = AdaBoostClassifier(
    n_estimators=100,
    random_state=42
)
adaboost_model.fit(
    X_train,
    y_train
)
y_pred = adaboost_model.predict(X_test)
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy :", accuracy)

Accuracy : 1.0

In [20]:
#15.4 voting 
from sklearn.ensemble import VotingClassifier
lr = LogisticRegression(
    max_iter=1000,
    random_state=42
)

tree = DecisionTreeClassifier(
    random_state=42
)

rf = RandomForestClassifier(
    random_state=42
)

In [21]:
voting_model = VotingClassifier(
    estimators=[
        ("lr", lr),
        ("tree", tree),
        ("rf", rf)
    ],
    voting="hard"
)

In [22]:
voting_model.fit(
    X_train,
    y_train
)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(max_iter=1000,
                                                 random_state=42)),
                             ('tree', DecisionTreeClassifier(random_state=42)),
                             ('rf', RandomForestClassifier(random_state=42))])

In [23]:
y_pred = voting_model.predict(
    X_test
)

In [24]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy :", accuracy)

Accuracy : 1.0

In [25]:
#15.5 stacking 
from sklearn.ensemble import StackingClassifier
lr = LogisticRegression(
    max_iter=1000,
    random_state=42
)

tree = DecisionTreeClassifier(
    random_state=42
)

rf = RandomForestClassifier(
    random_state=42
)

meta_model = LogisticRegression(
    random_state=42
)

In [26]:
stacking_model = StackingClassifier(
    estimators=[
        ("lr", lr),
        ("tree", tree),
        ("rf", rf)
    ],
    final_estimator=meta_model
)

In [27]:
stacking_model.fit(
    X_train,
    y_train
)

StackingClassifier(estimators=[('lr',
                                LogisticRegression(max_iter=1000,
                                                   random_state=42)),
                               ('tree',
                                DecisionTreeClassifier(random_state=42)),
                               ('rf', RandomForestClassifier(random_state=42))],
                   final_estimator=LogisticRegression(random_state=42))

In [28]:
y_pred = stacking_model.predict(
    X_test
)

In [29]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy :", accuracy)

Accuracy : 1.0

In [31]:
#15,6 comparioson of these 4 modals 

bagging_pred = bagging_model.predict(X_test)

bagging_acc = accuracy_score(
    y_test,
    bagging_pred
)
adaboost_pred = adaboost_model.predict(X_test)

adaboost_acc = accuracy_score(
    y_test,
    adaboost_pred
)
voting_pred = voting_model.predict(X_test)

voting_acc = accuracy_score(
    y_test,
    voting_pred
)
stacking_pred = stacking_model.predict(X_test)

stacking_acc = accuracy_score(
    y_test,
    stacking_pred
)
comparison = pd.DataFrame({
    "Model":[
        "Bagging",
        "AdaBoost",
        "Voting",
        "Stacking"
    ],
    "Accuracy":[
        bagging_acc,
        adaboost_acc,
        voting_acc,
        stacking_acc
    ]
})

comparison.sort_values(
    by="Accuracy",
    ascending=False
)

      Model  Accuracy
0   Bagging       1.0
1  AdaBoost       1.0
2    Voting       1.0
3  Stacking       1.0

In [32]:
#feature importance 15.7
rf = RandomForestClassifier(
    random_state=42
)

rf.fit(
    X_train,
    y_train
)
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance.head(10)

                                           Feature  Importance
1                    Financial Loss (in Million $)    0.838575
2                         Number of Affected Users    0.027549
3              Incident Resolution Time (in Hours)    0.024242
0                                             Year    0.017147
29            Security Vulnerability Type_Zero-day    0.004142
28      Security Vulnerability Type_Weak Passwords    0.004056
31               Defense Mechanism Used_Encryption    0.003810
32                 Defense Mechanism Used_Firewall    0.003778
27  Security Vulnerability Type_Unpatched Software    0.003767
24                           Attack Source_Insider    0.003660